import type { Metadata } from "next";
import { Playfair, Playfair_Display } from "@next/font/google"
import "./globals.css";

export const metadata: Metadata = {
  title: "Cue",
  description: "Generated by create next app",
};

const font = Playfair_Display({
  subsets:['latin'],
  weight:['400','700']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
      </body>
    </html>
  );
}
